# Generated by Django 6.0.7 on 2026-07-30 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(default='Main Block', max_length=50)),
                ('floor', models.IntegerField(default=1)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.IntegerField(default=2)),
                ('occupancy_status', models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Vacant', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=3000.0, max_digits=8)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=5000.0, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='agreement_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warden_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('Rent Due', 'Rent Due Date'), ('Agreement Expiry', 'Agreement Expiry'), ('Check-in', 'Student Check-in'), ('Check-out', 'Student Check-out'), ('Complaint Follow-up', 'Complaint Follow-up'), ('Maintenance', 'Maintenance Schedule'), ('Visitor', 'Visitor Appointment')], max_length=30)),
                ('event_date', models.DateTimeField()),
                ('google_event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('inspection_type', models.CharField(choices=[('Check-in', 'Check-in Inspection'), ('Check-out', 'Check-out Inspection')], max_length=15)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('furniture_condition', models.CharField(default='Good', max_length=50)),
                ('wall_condition', models.CharField(default='Good', max_length=50)),
                ('electrical_condition', models.CharField(default='Good', max_length=50)),
                ('bathroom_condition', models.CharField(default='Good', max_length=50)),
                ('inventory_checklist', models.TextField(default='Bed, Desk, Chair, Fan, Light', help_text='Items verified: Bed, Desk, Chair, Fan, Light')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='room_inspections/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='room_inspections/')),
                ('damage_notes', models.TextField(blank=True, null=True)),
                ('damage_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_received', models.DecimalField(decimal_places=2, default=5000.0, max_digits=8)),
                ('damage_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=5000.0, max_digits=8)),
                ('status', models.CharField(choices=[('Held', 'Held'), ('Partially Refunded', 'Partially Refunded'), ('Refunded', 'Refunded')], default='Held', max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposit_record', to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Photograph', 'Student Photograph'), ('CNIC_Front', 'CNIC / Passport (Front)'), ('CNIC_Back', 'CNIC / Passport (Back)'), ('Guardian_CNIC', 'Parent/Guardian CNIC'), ('Admission_Form', 'Admission Form'), ('Hostel_Agreement', 'Hostel Agreement Form'), ('Emergency_Contact', 'Emergency Contact Info'), ('Supporting_Doc', 'Supporting Document')], max_length=30)),
                ('file', models.FileField(upload_to='student_docs/')),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=150)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('enrollment_date', models.DateField()),
                ('billing_cycle_start', models.DateField()),
                ('billing_cycle_end', models.DateField()),
                ('due_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, default=3000.0, max_digits=8)),
                ('electricity_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='hostel.student')),
            ],
        ),
    ]
