# Generated by Django 6.0.7 on 2026-07-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hostelroom_student_agreement_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_no',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
