# Generated by Django 6.0.7 on 2026-07-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_student_enrollment_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
