# Generated by Django 6.0.7 on 2026-08-04 09:16

import django.db.models.deletion
import hostel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNIC/B-Form'),
        ),
        migrations.CreateModel(
            name='StudentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_text', models.TextField(default=hostel.models.default_contract_text)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_text', models.CharField(blank=True, help_text='Digital signature of the student (typed name)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='hostel.student')),
            ],
        ),
    ]
