# Generated by Django 6.0.7 on 2026-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_student_cnic_studentcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelroom',
            name='has_ac',
            field=models.BooleanField(default=False, help_text='Does this room have an Air Conditioner?'),
        ),
    ]
