# Generated by Django 6.0.7 on 2026-08-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_hostelroom_has_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='ac_unit_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit for AC electricity calculation', max_digits=6),
        ),
        migrations.AddField(
            model_name='voucher',
            name='final_meter_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='initial_meter_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_ac_room',
            field=models.BooleanField(default=False),
        ),
    ]
