from django.db import models
from django.contrib.auth.models import User
from datetime import date
import uuid

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15)
    gender = models.CharField(max_length=10)
    address = models.TextField()
    room_no = models.CharField(max_length=10)
    rent_price = models.CharField(max_length=10, default="3000")
    rent_status = models.BooleanField(default=False)
    join_date = models.DateField(auto_now_add=True)
    
    # Enhanced Student Fields - Autogenerated Enrollment Number
    enrollment_no = models.CharField(max_length=50, unique=True, blank=True, null=True, editable=False)
    cnic = models.CharField("CNIC/B-Form", max_length=20, null=True, blank=True)
    leaving_date = models.DateField(null=True, blank=True)
    deposit_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    agreement_expiry = models.DateField(null=True, blank=True)
    assigned_warden = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="warden_students")

    def save(self, *args, **kwargs):
        if not self.enrollment_no:
            year_str = date.today().strftime("%Y")
            count = Student.objects.count() + 1
            unique_suffix = uuid.uuid4().hex[:4].upper()
            self.enrollment_no = f"HST-{year_str}-{count:03d}-{unique_suffix}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} ({self.enrollment_no or 'No ID'}) | Room: {self.room_no}"


DOCUMENT_TYPE_CHOICES = [
    ('Photograph', 'Student Photograph'),
    ('CNIC_Front', 'CNIC / Passport (Front)'),
    ('CNIC_Back', 'CNIC / Passport (Back)'),
    ('Guardian_CNIC', 'Parent/Guardian CNIC'),
    ('Admission_Form', 'Admission Form'),
    ('Hostel_Agreement', 'Hostel Agreement Form'),
    ('Emergency_Contact', 'Emergency Contact Info'),
    ('Supporting_Doc', 'Supporting Document'),
]

VERIFICATION_STATUS_CHOICES = [
    ('Pending', 'Pending Verification'),
    ('Verified', 'Verified'),
    ('Rejected', 'Rejected'),
]

class StudentDocument(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="documents")
    doc_type = models.CharField(max_length=30, choices=DOCUMENT_TYPE_CHOICES)
    file = models.FileField(upload_to="student_docs/")
    verification_status = models.CharField(max_length=15, choices=VERIFICATION_STATUS_CHOICES, default="Pending")
    expiry_date = models.DateField(null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    rejection_reason = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.student.name} - {self.get_doc_type_display()} ({self.verification_status})"


class HostelRoom(models.Model):
    building_name = models.CharField(max_length=50, default="Main Block")
    floor = models.IntegerField(default=1)
    room_number = models.CharField(max_length=20, unique=True)
    capacity = models.IntegerField(default=2)
    occupancy_status = models.CharField(
        max_length=20, 
        choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], 
        default='Vacant'
    )
    monthly_rent = models.DecimalField(max_digits=8, decimal_places=2, default=3000.00)
    security_deposit = models.DecimalField(max_digits=8, decimal_places=2, default=5000.00)
    has_ac = models.BooleanField(default=False, help_text="Does this room have an Air Conditioner?")

    def __str__(self):
        return f"Room {self.room_number} ({self.building_name} - Floor {self.floor})"


INSPECTION_TYPE_CHOICES = [
    ('Check-in', 'Check-in Inspection'),
    ('Check-out', 'Check-out Inspection'),
]

class RoomInspection(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="inspections")
    room_number = models.CharField(max_length=20)
    inspection_type = models.CharField(max_length=15, choices=INSPECTION_TYPE_CHOICES)
    inspection_date = models.DateTimeField(auto_now_add=True)
    furniture_condition = models.CharField(max_length=50, default="Good")
    wall_condition = models.CharField(max_length=50, default="Good")
    electrical_condition = models.CharField(max_length=50, default="Good")
    bathroom_condition = models.CharField(max_length=50, default="Good")
    inventory_checklist = models.TextField(help_text="Items verified: Bed, Desk, Chair, Fan, Light", default="Bed, Desk, Chair, Fan, Light")
    photo_1 = models.ImageField(upload_to="room_inspections/", null=True, blank=True)
    photo_2 = models.ImageField(upload_to="room_inspections/", null=True, blank=True)
    damage_notes = models.TextField(blank=True, null=True)
    damage_charges = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)

    def __str__(self):
        return f"{self.student.name} - Room {self.room_number} ({self.inspection_type})"


VOUCHER_STATUS_CHOICES = [
    ('Unpaid', 'Unpaid'),
    ('Paid', 'Paid'),
    ('Overdue', 'Overdue'),
]

class Voucher(models.Model):
    # Autogenerated Voucher Number
    voucher_no = models.CharField(max_length=50, unique=True, blank=True, editable=False)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="vouchers")
    enrollment_date = models.DateField()
    billing_cycle_start = models.DateField()
    billing_cycle_end = models.DateField()
    due_date = models.DateField()
    rent_amount = models.DecimalField(max_digits=8, decimal_places=2, default=3000.00)
    electricity_charges = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    other_charges = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    total_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    status = models.CharField(max_length=10, choices=VOUCHER_STATUS_CHOICES, default='Unpaid')
    
    # AC Meter Reading Fields
    is_ac_room = models.BooleanField(default=False)
    initial_meter_reading = models.IntegerField(null=True, blank=True)
    final_meter_reading = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.voucher_no:
            month_str = date.today().strftime("%Y%m")
            count = Voucher.objects.count() + 1
            unique_suffix = uuid.uuid4().hex[:4].upper()
            self.voucher_no = f"VCH-{month_str}-{count:03d}-{unique_suffix}"
            
        # AC electricity calculation
        if self.is_ac_room and self.initial_meter_reading is not None and self.final_meter_reading is not None:
            if self.final_meter_reading >= self.initial_meter_reading:
                company = CompanySettings.objects.first()
                rate = company.ac_unit_rate if company else 0
                
                # Dynamic check for shared room occupancy
                occupancy = Student.objects.filter(room_no=self.student.room_no, leaving_date__isnull=True).count()
                occupancy = max(1, occupancy)
                
                from decimal import Decimal
                total_electricity = Decimal(self.final_meter_reading - self.initial_meter_reading) * rate
                self.electricity_charges = total_electricity / Decimal(occupancy)
        
        self.total_amount = (self.rent_amount or 0) + (self.electricity_charges or 0) + (self.other_charges or 0)
        
        super().save(*args, **kwargs)

        # Automatically update student rent status based on voucher status
        # Since a student may have multiple vouchers, we update rent_status = True
        # if this voucher is Paid. If they have outstanding Unpaid/Overdue vouchers, 
        # we mark rent_status = False. 
        # But a simple rule: if we are saving this voucher as Paid, we assume they paid their current dues.
        if self.status == 'Paid':
            self.student.rent_status = True
            self.student.save()

            # Automate RentPaymentHistory
            RentPaymentHistory.objects.update_or_create(
                student=self.student,
                month=self.billing_cycle_start.strftime("%B %Y"),
                defaults={
                    'amount': self.total_amount,
                    'amount_paid': self.total_amount,
                    'remaining_amount': 0.00,
                    'date_paid': date.today(),
                    'status': 'paid'
                }
            )
        elif self.status in ['Unpaid', 'Overdue']:
            self.student.rent_status = False
            self.student.save()

    def __str__(self):
        return f"Voucher #{self.voucher_no} - {self.student.name} ({self.status})"


EVENT_TYPE_CHOICES = [
    ('Rent Due', 'Rent Due Date'),
    ('Agreement Expiry', 'Agreement Expiry'),
    ('Check-in', 'Student Check-in'),
    ('Check-out', 'Student Check-out'),
    ('Complaint Follow-up', 'Complaint Follow-up'),
    ('Maintenance', 'Maintenance Schedule'),
    ('Visitor', 'Visitor Appointment'),
]

class CalendarEvent(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True, blank=True, related_name="calendar_events")
    title = models.CharField(max_length=150)
    event_type = models.CharField(max_length=30, choices=EVENT_TYPE_CHOICES)
    event_date = models.DateTimeField()
    google_event_id = models.CharField(max_length=100, blank=True, null=True)
    reminder_sent = models.BooleanField(default=False)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"[{self.event_type}] {self.title} on {self.event_date.strftime('%Y-%m-%d')}"


class Visitor(models.Model):
    visitor_name = models.CharField(max_length=100)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="visitors")
    phone = models.CharField(max_length=15)
    photo = models.ImageField(upload_to="visitors/", null=True, blank=True)
    check_in = models.DateTimeField(auto_now_add=True)
    check_out = models.DateTimeField(null=True, blank=True)
    purpose = models.CharField(max_length=150)

    def __str__(self):
        return f"{self.visitor_name} visiting {self.student.name}"


class SecurityDeposit(models.Model):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name="security_deposit_record")
    deposit_received = models.DecimalField(max_digits=8, decimal_places=2, default=5000.00)
    damage_deduction = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    refund_amount = models.DecimalField(max_digits=8, decimal_places=2, default=5000.00)
    status = models.CharField(
        max_length=20, 
        choices=[('Held', 'Held'), ('Partially Refunded', 'Partially Refunded'), ('Refunded', 'Refunded')], 
        default='Held'
    )

    def __str__(self):
        return f"{self.student.name} Deposit: PKR {self.refund_amount} ({self.status})"


class Complaint(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    msg = models.TextField()
    date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=20, default='Pending')
    response = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.student.name} |-| {self.subject} |-| {self.date} |-| {self.status}" 

class RentPaymentHistory(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    month = models.CharField(max_length=20)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    amount_paid = models.DecimalField(max_digits=8, decimal_places=2)
    remaining_amount = models.DecimalField(max_digits=8, decimal_places=2)
    date_paid = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=[('paid', 'paid'), ('unpaid', 'unpaid')])

    def __str__(self):
        return f"{self.student.name} |-| {self.date_paid} |-| {self.status}"




class Contact(models.Model):
    name = models.CharField(max_length=50)
    mobile_number = models.CharField(max_length=15)
    visitor_email = models.EmailField()
    msg = models.TextField(blank=True, null=True)
    contact_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}  |-|  {self.contact_date}  |-|  {self.visitor_email}"

class CompanySettings(models.Model):
    name = models.CharField(max_length=150, default="Hostel Management System")
    address = models.TextField(blank=True, null=True)
    contact_number = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    logo = models.ImageField(upload_to="company_logos/", blank=True, null=True)
    ac_unit_rate = models.DecimalField(max_digits=6, decimal_places=2, default=0.00, help_text="Price per unit for AC electricity calculation")

    class Meta:
        verbose_name_plural = "Company Settings"

    def __str__(self):
        return self.name

def default_contract_text():
    return """**HOSTEL ACCOMMODATION AGREEMENT**

This Agreement is entered into between the Hostel Administration and the Student.

**1. ALLOCATION OF ROOM**
The student is allocated a room based on availability and agrees to adhere to the room assignment.

**2. RENT AND PAYMENTS**
The student agrees to pay the monthly rent and any associated utility charges on or before the due date each month. Failure to pay may result in late fees or eviction.

**3. DISCIPLINE AND CONDUCT**
- The student must maintain a peaceful environment.
- Ragging, smoking, alcohol, and illegal substances are strictly prohibited.
- Damage to hostel property will be fined and deducted from the security deposit.

**4. TERMINATION OF AGREEMENT**
The administration reserves the right to terminate this agreement and evict the student without prior notice in case of severe misconduct or continuous default on payments.

By signing below, I acknowledge that I have read, understood, and agree to abide by all the rules and regulations of the hostel.
"""

class StudentContract(models.Model):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name="contract")
    contract_text = models.TextField(default=default_contract_text)
    is_signed = models.BooleanField(default=False)
    signed_at = models.DateTimeField(null=True, blank=True)
    signature_text = models.CharField(max_length=255, null=True, blank=True, help_text="Digital signature of the student (typed name)")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        status = "Signed" if self.is_signed else "Unsigned"
        return f"Contract for {self.student.name} ({status})"



class LeaveNotice(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="leave_notices")
    notice_date = models.DateField(auto_now_add=True)
    planned_leaving_date = models.DateField()
    reason = models.TextField(blank=True, null=True)
    status = models.CharField(
        max_length=20,
        choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')],
        default='Pending'
    )
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def eligible_for_refund(self):
        if self.notice_date and self.planned_leaving_date:
            return (self.planned_leaving_date - self.notice_date).days >= 30
        return False

    def __str__(self):
        return f"Leave Notice: {self.student.name} for {self.planned_leaving_date}"
